name: Release

on:
  push:
    branches:
      - private

jobs:
  release:
    if: github.repository == 'tatukoivisto/nextra'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --filter @tatukoivisto/nextra

      - name: Clean
        run: pnpm clean

      - name: Build
        run: pnpm build:core

      - name: Type Check
        run: pnpm types:check

      - name: Creating .npmrc for GitHub Packages
        run: |
          cat << EOF > "$HOME/.npmrc"
            @tatukoivisto:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$GH_PACKAGES_TOKEN
          EOF
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm run version # should be `pnpm run`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
